spring.application.name=barber-booking

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/barber_booking_db?createDatabaseIfNotExist=true
spring.datasource.username=<your_database_username>
spring.datasource.password=<your_database_password>
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=<Your_JWT_Secret_Key>

# Validità di 24 ore
jwt.expiration=86400000


#JavaMailSender
app.mail.from=noreply@barberbooking.com
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=<Your_Username>
spring.mail.password=<Your_Password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000